[package]
name = "Livermore-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.5", features = ["full"] }
yahoo_finance_api = "1.3.0"
tokio-test = "0.4.2"
time = "0.3.20"
